resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - db-pvc.yaml
  - media-pvc.yaml
images:
  - name: nspeerstra/portfolio-django
    newTag: 0.5.0
